version: '3.8'
services:
  frontend:
    image: ${PLANTS_FRONTEND_IMAGE}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plants.rule=Host(`plants.heatherward.dev`,`www.plants.heatherward.dev`)"
      - "traefik.http.routers.plants.entrypoints=https"
      - "traefik.http.routers.plants.tls.certresolver=cloudflaredns"
      - "traefik.http.services.plants.loadbalancer.server.port=80"
    networks:
      - proxy
    volumes:
      - ${PLANTS_SRV_BASE}/sites-available:/etc/nginx/sites-enabled
networks:
  proxy:
    external: true
